// Generated by CoffeeScript 2.0.0-beta8
ApplicationService.factory('fhpxAPI', function ($http) {
  var fhpxAPI, KEY;
  KEY = { fhpx: 'pcVeKhKdsQoORanPjZGnGz9Li0XGiihd2X7XnBJj' };
  fhpxAPI = function (options) {
    this.photos = [];
    this.busy = false;
    this.category = options.category;
  };
  fhpxAPI.prototype.nextPage = function () {
    var url;
    if (this.busy)
      return;
    this.busy = true;
    if (!this.page)
      this.page = 1;
    url = 'https://api.500px.com/v1/photos?feature=' + this.category + '&page=' + this.page + '&rpp=20&exclude=nude&image_size[]=3&image_size[]=4&consumer_key=' + KEY.fhpx;
    $http.get(url).success(function (this$) {
      return function (data) {
        this$.photos = this$.photos.concat(data.photos);
        this$.page = this$.page + 1;
        this$.busy = false;
      };
    }(this));
  };
  return fhpxAPI;
});
