// Generated by CoffeeScript 2.0.0-beta8
angular.module('CollectiveApp.services', []).factory('fhpxAPI', function ($http) {
  var fhpxAPI, KEY;
  KEY = { fhpx: 'pcVeKhKdsQoORanPjZGnGz9Li0XGiihd2X7XnBJj' };
  fhpxAPI = function () {
    this.photos = [];
    this.busy = false;
  };
  fhpxAPI.prototype.nextPage = function () {
    var url;
    if (this.busy)
      return;
    this.busy = true;
    if (!this.page)
      this.page = 1;
    url = 'https://api.500px.com/v1/photos?feature=editors&page=' + this.page + '&image_size[]=3&image_size[]=4&consumer_key=' + KEY.fhpx;
    $http.get(url).success(function (this$) {
      return function (data) {
        var i, photos;
        photos = data.photos;
        i = 0;
        while (i < photos.length) {
          this$.photos.push(photos[i]);
          i++;
        }
        this$.page = this$.page + 1;
        this$.busy = false;
      };
    }(this).bind(this));
  };
  return fhpxAPI;
});
