// Generated by CoffeeScript 2.0.0-beta8
ApplicationService.factory('fhpxAPI', function ($http) {
  var fhpxAPI, KEY;
  KEY = { fhpx: 'pcVeKhKdsQoORanPjZGnGz9Li0XGiihd2X7XnBJj' };
  fhpxAPI = function (options) {
    this.photos = [];
    this.loading = $('<div class="loading"><div></div><div></div><div></div><div></div></div>');
    this.busy = false;
    this.category = options.category;
    this.only = options.only;
    this.exclude = options.category !== 'Nude' ? '' : 'Nude';
  };
  fhpxAPI.prototype.firstPage = function () {
    var url;
    $('#grids').parent().append(this.loading);
    url = 'https://api.500px.com/v1/photos?feature=' + this.category + '&page=' + this.page + '&only=' + encodeURIComponent(this.only) + '&rpp=40&exclude=' + this.exclude + '&image_size[]=3&image_size[]=4&consumer_key=' + KEY.fhpx;
    $http.get(url).success(function (this$) {
      return function (data) {
        this$.photos = this$.photos.concat(data.photos);
        window.localStorage.setItem('ca_photos', JSON.stringify(this$.photos));
        $('.loading').remove();
      };
    }(this));
  };
  fhpxAPI.prototype.nextPage = function () {
    var url;
    if (this.busy)
      return;
    $('#grids').parent().append(this.loading);
    this.busy = true;
    if (!this.page)
      this.page = 2;
    url = 'https://api.500px.com/v1/photos?feature=' + this.category + '&page=' + this.page + '&only=' + encodeURIComponent(this.only) + '&rpp=40&exclude=' + this.exclude + '&image_size[]=3&image_size[]=4&consumer_key=' + KEY.fhpx;
    $http.get(url).success(function (this$) {
      return function (data) {
        this$.photos = this$.photos.concat(data.photos);
        this$.page = this$.page + 1;
        this$.busy = false;
        $('.loading').remove();
      };
    }(this));
  };
  return fhpxAPI;
});
