// Generated by CoffeeScript 2.0.0-beta8
angular.module('CollectiveApp.services', []).factory('dribbleAPI', function ($http) {
  var dribbleAPI;
  dribbleAPI = {};
  dribbleAPI.getShots = function () {
    return $http.get('../assets/data/everyone.json');
  };
  return dribbleAPI;
});
