// Generated by CoffeeScript 2.0.0-beta8
ApplicationService.factory('dribbleAPI', function ($http) {
  var API;
  API = function (options) {
    this.photos = [];
    this.busy = false;
    this.category = options.category;
  };
  API.prototype.nextPage = function () {
    var url;
    if (this.busy)
      return;
    this.busy = true;
    if (!this.page)
      this.page = 1;
    url = 'http://api.dribbble.com/shots/' + this.category + '?page=' + this.page + '&per_page=20';
    $http.get(url).success(function (this$) {
      return function (data) {
        this$.photos = this$.photos.concat(data.shots);
        this$.page = this$.page + 1;
        this$.busy = false;
      };
    }(this));
  };
  return API;
});
