// Generated by CoffeeScript 2.0.0-beta8
ApplicationService.factory('dribbleAPI', function ($http) {
  var API;
  API = function (options) {
    this.photos = [];
    this.busy = false;
    this.category = options.category;
  };
  API.prototype.nextPage = function () {
    var loading, url;
    if (this.busy)
      return;
    loading = $('<div class="loading"><div></div><div></div><div></div><div></div></div>');
    $('#grids').parent().append(loading);
    this.busy = true;
    if (!this.page)
      this.page = 1;
    url = 'https://api.dribbble.com/shots/' + this.category + '?page=' + this.page + '&per_page=40&callback=JSON_CALLBACK';
    $http.jsonp(url).success(function (this$) {
      return function (data) {
        this$.photos = this$.photos.concat(data.shots);
        this$.page = this$.page + 1;
        this$.busy = false;
        $('.loading').remove();
      };
    }(this));
  };
  return API;
});
