// Generated by CoffeeScript 2.0.0-beta8
ApplicationService.factory('instagramAPI', function ($http, $location) {
  var instagramAPI, USER;
  USER = {
    accessId: '255614267',
    clientId: 'fadd55ae5bf148c8b0f36d9f3d824d46'
  };
  instagramAPI = function (options) {
    var base_url;
    if (!_.isNull(window.localStorage.getItem('in_user')))
      this.access_token = JSON.parse(window.localStorage.getItem('in_user')).access_token;
    this.photos = [];
    this.profile = [];
    this.users = [];
    this.loading = $('<div class="loading-heart-container"><div class="loading-heart"></div></div>');
    this.busy = false;
    base_url = 'https://api.instagram.com/v1';
    console.log(options.filter);
    switch (options.filter) {
    case 'feed':
      this.url = '' + base_url + '/users/self/feed?count=10&access_token=' + this.access_token;
      break;
    case 'popular':
      this.url = '' + base_url + '/media/popular?client_id=' + USER.clientId;
      break;
    case 'follows':
      this.url = '' + base_url + '/users/' + options.user_id + '/follows?access_token=' + this.access_token;
      break;
    case 'followed-by':
      this.url = '' + base_url + '/users/' + options.user_id + '/followed-by?access_token=' + this.access_token;
      break;
    case 'user_id':
      this.url = '' + base_url + '/users/' + options.user_id + '/media/recent?access_token=' + this.access_token;
      break;
    case 'recent':
      this.url = '' + base_url + '/users/' + options.user_id + '/media/' + options.filter + '?count=30&access_token=' + this.access_token;
      break;
    case 'liked':
      this.url = '' + base_url + '/users/self/media/' + options.filter + '?count=30&access_token=' + this.access_token;
    }
  };
  instagramAPI.prototype.fetchUsers = function (params) {
    var profile_url;
    $('#instagram').parent().append(this.loading);
    this.loading.css({
      'margin-top': '50px',
      'margin-bottom': '50px'
    });
    profile_url = 'https://api.instagram.com/v1/users/' + params.user_id + '?access_token=' + this.access_token;
    $http.get(profile_url).success(function (this$) {
      return function (data) {
        this$.profile = data.data;
        return $http.get(this$.url).success(function (this$1) {
          return function (data) {
            this$1.users = this$1.users.concat(data.data);
            $('.loading-heart-container').remove();
          };
        }(this$));
      };
    }(this));
  };
  instagramAPI.prototype.firstPage = function (params) {
    var profile_url;
    $('#instagram').parent().append(this.loading);
    profile_url = 'https://api.instagram.com/v1/users/' + params.user_id + '?access_token=' + this.access_token;
    $http.get(profile_url).success(function (this$) {
      return function (data) {
        this$.profile = data.data;
        return $http.get(this$.url).success(function (this$1) {
          return function (data) {
            this$1.next_url = data.pagination.next_url;
            this$1.photos = this$1.photos.concat(data.data);
            window.localStorage.setItem('in_photos', JSON.stringify(this$1.photos));
            $('.loading-heart-container').remove();
          };
        }(this$));
      };
    }(this));
  };
  instagramAPI.prototype.likeToggle = function (params) {
    var like_url;
    like_url = 'https://api.instagram.com/v1/media/' + params.media_id + '/likes?access_token=' + this.access_token;
    if (params.method === 'post') {
      $http.post(like_url);
    } else {
      $http({
        url: like_url,
        method: 'DELETE'
      });
    }
  };
  instagramAPI.prototype.comment = function (params) {
    var comment_url, object;
    comment_url = 'https://api.instagram.com/v1/media/' + params.media_id + '/comments';
    object = {
      access_token: this.access_token,
      text: params.text
    };
    if (params.method === 'post') {
      $.post(comment_url, object).success(function (data) {
        return console.log('Commenting ' + data + ' ...');
      });
    } else {
      $http({
        url: comment_url,
        method: 'DELETE'
      });
    }
  };
  instagramAPI.prototype.login = function () {
    var login_url, redirect;
    redirect = 'https://nfcimppfkbpdohcgpdifipajpbahncnc.chromiumapp.org/provider_cb';
    login_url = 'https://api.instagram.com/oauth/authorize/?client_id=' + USER.clientId + '&redirect_uri=' + redirect + '&response_type=token&scope=likes+comments+relationships';
    chrome.identity.launchWebAuthFlow({
      url: login_url,
      interactive: true
    }, function (responseUrl) {
      console.log(responseUrl);
      window.localStorage.setItem('in_user', JSON.stringify({ access_token: responseUrl.split('#access_token=')[1] }));
      return $location.path('/instagram/feed');
    });
  };
  instagramAPI.prototype.nextPage = function () {
    if (this.busy)
      return;
    $('#instagram').parent().append(this.loading);
    this.busy = true;
    if (!this.page)
      this.page = 2;
    $http.get(this.next_url).success(function (this$) {
      return function (data) {
        this$.next_url = data.pagination.next_url;
        this$.photos = this$.photos.concat(data.data);
        this$.page = this$.page + 1;
        this$.busy = false;
        $('.loading-heart-container').remove();
      };
    }(this));
  };
  return instagramAPI;
});
