// Generated by CoffeeScript 2.0.0-beta8
ApplicationDirective.directive('ngRepeatEnd', function ($timeout) {
  return {
    restrict: 'A',
    link: function (scope, element, attr) {
      if (scope.$last === true)
        $timeout(function () {
          scope.$emit('show');
        });
    }
  };
});
ApplicationDirective.directive('whenScrolled', function ($timeout) {
  return {
    restrict: 'A',
    link: function (scope, element, attr) {
      $timeout(function () {
        var raw;
        raw = element[0];
        return $(window).bind('scroll', function () {
          if (raw.scrollTop + raw.offsetHeight >= raw.scrollHeight) {
            scope.$apply(attr.whenScrolled);
            return;
          }
        });
      }, 300);
    }
  };
});
ApplicationDirective.directive('infiScroll', function ($timeout) {
  return {
    restrict: 'A',
    link: function (scope, elm, attr) {
      $timeout(function () {
        var callMore, handler, newHeight;
        callMore = true;
        newHeight = void 0;
        handler = function () {
          var docHeight, elmHeight, scrolledHeight, winHeight;
          docHeight = $(document).height();
          winHeight = $(window).height() + 1e3;
          scrolledHeight = $(document).scrollTop();
          elmHeight = $(elm).height();
          (function () {
            if (docHeight <= winHeight + scrolledHeight)
              if (!(newHeight === elmHeight)) {
                scope.$eval(attr.infiScroll);
                newHeight = elmHeight;
              }
          }());
        };
        $(document).on('scroll', handler);
        scope.$on('$destroy', function () {
          return $(document).off('scroll', handler);
        });
      }, 300);
    }
  };
});
