// Generated by CoffeeScript 2.0.0-beta8
ApplicationDirective.directive('onLoad', function () {
  return {
    link: function (scope, element, attrs) {
      element.bind('load', function (e) {
        var img;
        if (element.parent().parent().parent().hasClass('shot-cam-loader')) {
          img = element.parent().parent().parent();
        } else {
          img = element.parent().parent();
        }
        img.removeClass('shot-cam-loader');
        $('.spinner', img).fadeOut();
      });
    }
  };
});
