// Generated by CoffeeScript 2.0.0-beta8
ApplicationDirective.directive('onLoad', function () {
  return {
    link: function (scope, element, attrs) {
      element.bind('load', function (e) {
        var img;
        img = $('.shot-cam-loader');
        img.removeClass('shot-cam-loader');
        $('.spinner', img).fadeOut();
      });
    }
  };
});
