// Generated by CoffeeScript 2.0.0-beta8
ApplicationController.controller('500pxController', function ($scope, fhpxAPI, $routeParams) {
  $scope.setActive([
    'fhpx',
    $routeParams.category
  ]);
  $scope.service = new fhpxAPI({ category: $routeParams.category });
  $scope.service.nextPage();
});
