// Generated by CoffeeScript 2.0.0-beta8
ApplicationController.controller('500pxController', function ($scope, $location, fhpxAPI, $routeParams) {
  var path;
  console.log('Scope', $scope);
  console.log('fhpxAPI', fhpxAPI);
  console.log('$routeParams', $routeParams);
  console.log('$location', $location);
  path = $location.path().split('/')[2];
  $scope.setActive([
    'fhpx',
    path
  ]);
  $scope.service = new fhpxAPI({ category: path });
  $scope.service.nextPage();
});
