// Generated by CoffeeScript 2.0.0-beta8
ApplicationController.controller('ApplicationController', function ($scope) {
  var activityIndicatorOff, activityIndicatorOn, captionOff, captionOn, closeButtonOff, closeButtonOn, overlayOff, overlayOn;
  $scope.lightboxActive = false;
  $scope.setActive = function (options) {
    if (null == options)
      options = [];
    $scope.fhpxActive = '';
    $scope.popularActive = '';
    $scope.upcomingActive = '';
    $scope.editorsActive = '';
    $scope.fresh_todayActive = '';
    $scope.dribbleActive = '';
    $scope.instagramActive = '';
    $scope.feedActive = '';
    $scope.likedActive = '';
    $scope.recentActive = '';
    return angular.forEach(options, function (key, value) {
      return $scope[key + 'Active'] = 'btn-active';
    });
  };
  $scope.toggleSettings = function () {
    $('#settings').toggle();
    return $('.container-fluid > .row:first-child').toggleClass('inactive');
  };
  $scope.$on('show', function (event) {
    var current_scope;
    current_scope = $scope.$$listeners.show[0]['arguments'][0].targetScope;
    $('.cd-timeline-block').each(function () {
      if ($(this).offset().top > $(window).scrollTop() + $(window).height() * .75)
        $(this).find('.cd-timeline-img, .cd-timeline-content').addClass('is-hidden');
    });
    $('.timeline-img a', '#instagram').fluidbox();
    $('.loading').remove();
    if ($(window).width() > 1500) {
      $('.grid').addClass('col-md-2');
    } else {
      $('.grid').addClass('col-md-3');
    }
    if ($('#grids').data('grid') === 'user')
      $('.grid').removeClass('col-md-2 col-md-3').addClass('col-md-4');
    if ($('#grids').length > 0)
      new AnimOnScroll(document.getElementById('grids'), {
        minDuration: .4,
        maxDuration: .7,
        viewportFactor: .2
      });
    if (current_scope.service.photos.length >= 40) {
      if ($scope.lightboxActive)
        $scope.lightboxModel.loadImages($('.grid a.lightbox'));
      if (!$scope.lightboxActive)
        $scope.lightbox();
    }
    console.log('Hey you! Bamboo seeker!');
    console.log("I'd like to hear from you :)");
    console.log('Talk to me @ richesrahul@gmail.com');
  });
  $scope.lightbox = function () {
    $scope.lightboxActive = true;
    $scope.lightboxModel = $('.grid a.lightbox').imageLightbox({
      onStart: function () {
        overlayOn();
      },
      onLoadStart: function () {
        activityIndicatorOn();
      },
      onLoadEnd: function () {
        activityIndicatorOff();
      },
      onEnd: function () {
        overlayOff();
        activityIndicatorOff();
      }
    });
  };
  activityIndicatorOn = function () {
    $('<div id="imagelightbox-loading"><div></div></div>').appendTo('body');
  };
  activityIndicatorOff = function () {
    $('#imagelightbox-loading').remove();
  };
  overlayOn = function () {
    $('<div id="imagelightbox-overlay"></div>').appendTo('body');
  };
  overlayOff = function () {
    $('#imagelightbox-overlay').remove();
  };
  closeButtonOn = function (instance) {
    $('<a href="#" id="imagelightbox-close">Close</a>').appendTo('body').on('click', function () {
      $(this).remove();
      instance.quitImageLightbox();
      return false;
    });
  };
  closeButtonOff = function () {
    $('#imagelightbox-close').remove();
  };
  captionOn = function () {
    var description;
    description = $('a[href="' + $('#imagelightbox').attr('src') + '"] img').attr('alt');
    if (description.length > 0)
      $('<div id="imagelightbox-caption">' + description + '</div>').appendTo('body');
  };
  return captionOff = function () {
    $('#imagelightbox-caption').remove();
  };
});
