// Generated by CoffeeScript 2.0.0-beta8
ApplicationController.controller('BookmarkController', function ($scope) {
  $scope.template = {
    name: 'bookmark_view',
    path: 'templates/bookmark_view.html'
  };
  return console.log('bookmarks..!');
});
