// Generated by CoffeeScript 2.0.0-beta8
angular.module('CollectiveApp.controllers', []).controller('dribbleController', function ($scope, dribbleAPI) {
  $scope.shots = [];
  return dribbleAPI.getShots().success(function (response) {
    return $scope.shots = response.shots;
  });
});
