// Generated by CoffeeScript 2.0.0-beta8
ApplicationController.controller('DribbleController', function ($scope, dribbleAPI, $routeParams) {
  $scope.setActive([
    'dribble',
    $routeParams.category
  ]);
  $scope.service = new dribbleAPI({ category: $routeParams.category });
  $scope.service.nextPage();
});
