// Generated by CoffeeScript 2.0.0-beta8
ApplicationController.controller('InstagramController', function ($scope, $location, instagramAPI, $routeParams, $timeout) {
  $scope.service = new instagramAPI($routeParams);
  $scope.service.firstPage();
});
