// Generated by CoffeeScript 2.0.0-beta8
ApplicationController.controller('SettingsController', function ($scope) {
  $scope.template = 'templates/settings_view.html';
  $scope.showTab = function ($event) {
    var tab;
    tab = $($event.target);
    $('.nav-tabs li').removeClass('active');
    $('.tab-pane').removeClass('active');
    tab.parent().addClass('active');
    $(tab.data('pane')).addClass('active');
  };
});
